version: '3'

services:

  laravel:
    build:
      context: ./
      dockerfile: ./docker/Laravel/Dockerfile
    container_name: mygame-laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - my-game-networks

  nginx-laravel:
    build: ./docker/Nginx
    container_name: mygame-nginx-laravel
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "9990:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - my-game-networks

  redis:
    build: ./docker/Redis
    container_name: mygame-redis
    ports:
      - "6378:6379"
    networks:
      - my-game-networks

  postgresql:
    build: ./docker/PostgreSQL
    container_name: mygame-postgresql
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_DB: mygame
      POSTGRES_USER: mygame
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    volumes:
      - pgrdata:/var/lib/postgresql/mygame-data
    networks:
      - my-game-networks

  phppgadmin:
    build: ./docker/PhpPgAdmin
    container_name: mygame-phppgadmin
    ports:
      - "9092:80"
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgresql
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: mygame
    networks:
      - my-game-networks

networks:
  my-game-networks:
    driver: bridge
volumes:
  pgrdata:
